### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by liangshaung113** [cvlab-yonsei/FYI#1]
Hi, thank you for your awesome work!

Can I know the amount of VRAM capacity to conduct experiments or the type of GPU that you used for experiments.
Also, I am curious if there is a quantitative results for COCO dataset.

**Comment by Byunggwan-Son** [comment]
Hi,
Thank you for your interest in our work. All of our experiments were conducted using 8 NVIDIA 2080 Ti GPUs. Regarding the COCO dataset, we did not run any experiments on it, as we only focused on image classification tasks.
Thank you!
