### ISSUE TITLE
FYI vs. Random Flipping

### ISSUE THREAD

**Issue by liangshaung113** [cvlab-yonsei/FYI#7]
Hi authors,
Your work on FYI is remarkable. I’m curious about one comparison:
How does FYI’s flip-and-concatenate approach quantitatively and qualitatively compare to simpler strategies like random flipping without concatenation? Are there specific cases where random flipping might suffice?
Thanks for your consideration!

**Comment by Byunggwan-Son** [comment]
Hi there!

I appreciate your interest! The concatenation ensures that each update of synthetic images includes both the original and flipped versions. Flipping may provide some benefit for algorithms involving multiple update steps per synthetic image update (e.g., MTT). However, from earlier experiments, we observed that including the concatenation significantly boosts MTT's performance. Random flipping does not improve performance for other algorithms, such as gradient matching and distribution matching.

Thanks.
